# SOGo reverse proxy config for Apache
# This proxies /SOGo (and /SOGo.*) to the SOGo daemon via uwsgi protocol

<VirtualHost *:80>
    ServerAdmin admin@localhost
    DocumentRoot /usr/lib/GNUstep/SOGo/WebServerResources/
    ServerName sogo

    # SOGo
    ProxyPreserveHost On
    RequestHeader set "x-webobjects-server-port" "80"
    RequestHeader set "x-webobjects-server-name" "sogo"
    RequestHeader set "x-webobjects-server-url" "%{REQUEST_SCHEME}e://sogo"
    
    <Location /SOGo>
        RequestHeader set "x-webobjects-server-port" "80"
        RequestHeader set "x-webobjects-server-name" "sogo"
        RequestHeader set "x-webobjects-server-url" "%{REQUEST_SCHEME}e://sogo"
        
        ProxyPass uwsgi://127.0.0.1:20000/ retry=0
        ProxyPassReverse uwsgi://127.0.0.1:20000/
    </Location>

    <Location /SOGo.woa>
        ProxyPass uwsgi://127.0.0.1:20000/SOGo.woa retry=0
        ProxyPassReverse uwsgi://127.0.0.1:20000/SOGo.woa
    </Location>

    <Location />
        RequestHeader set "x-webobjects-server-port" "80"
        RequestHeader set "x-webobjects-server-name" "sogo"
        RequestHeader set "x-webobjects-server-url" "%{REQUEST_SCHEME}e://sogo"
        
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
    </Location>

    ErrorLog /var/log/apache2/sogo-error.log
    CustomLog /var/log/apache2/sogo-access.log combined
</VirtualHost>
